# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'LH_Demo_Pipeline'
    subscriptionId: '501ed6e4-13b6-472d-84bd-72926a2953bf'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'archba-demo'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName LH_Inspire_Demo_Project -linkedTemplateUri https://raw.githubusercontent.com/archunz/LH_Inspire_Demo/master/CreateWebApp/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'LH_Test_Pipeline_Deploy'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
